[profile.default]
src = "src"
out = "out"
libs = ["lib"]
evm_version = "Cancun"
optimizer = true
via_ir = true
prague = true

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
