name: test

on:
  pull_request:
  merge_group:
  push:
    branches: [main]

env:
  FOUNDRY_PROFILE: ci

jobs:
  check:
    strategy:
      fail-fast: true

    name: Foundry project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: "EOF run Forge build"
        id: build
        run: make build-eof

      - name: "EOF run Forge test"
        id: test
        run: make test-eof

      - name: "Legacy run Forge build"
        id: build
        run: make build-legacy

      - name: "Legacy run Forge test"
        id: test
        run: make test-legacy
